<a href="https://colab.research.google.com/github/georgebsmith-tech/dart-excercises-and-solutions/blob/master/Linear%20Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
class LinearModel:
    def __init__(self,*args):
        self.x=None
        self.y=None
    
    def train(self,x,y):
        self.x=np.array(x)
        self.y=np.array(y)
        self.n=len(self.x)
        self.x_sum=(self.x).sum()
        self.y_sum=(self.y).sum()
        self.sum_xy=(self.x*self.y).sum()
        self.x_squared_sum=(self.x**2).sum()
        self.nume=self.n*self.sum_xy-(self.x_sum*self.y_sum)
        self.denum=self.n*self.x_squared_sum-self.x_sum**2
        self.coef_=self.nume/self.denum
        self.intercept_=(self.y).mean()-self.coef_*(self.x).mean()
    
    
    def predict(self,x):
        return self.intercept_+ (self.coef_)*np.array(x)


In [0]:
2,4

(2, 4)

In [0]:
model1=LinearModel()

In [0]:
data=np.array([[4.2,8.4],[2.7,6.2],[8.9,12.5],
              [8.2,10.5],[10.2,13]])

In [0]:
data.ndim

2

In [0]:
data.shape

(5, 2)

In [0]:
data.dtype

dtype('float64')

In [0]:
data.size

10

In [0]:
data

array([[ 4.2,  8.4],
       [ 2.7,  6.2],
       [ 8.9, 12.5],
       [ 8.2, 10.5],
       [10.2, 13. ]])

In [0]:
x=data[:,0]
y=data[:,1]

In [0]:

model1.train(x,y)

In [0]:
model1.predict([12.5])

array([15.012547])

In [0]:
model1.predict([12.5,10,29])

array([15.012547  , 12.85152801, 29.27527234])

In [0]:
model1.predict([12.5,10,29])